### ISSUE TITLE
Unable to evolve after using a commander dropped lifeform egg

### ISSUE THREAD

**Issue by 0sm1um** [NS2CDT/NS2Plus#18] opened 2019-01-07 14:52 UTC
After evolving to a higher lifeform, via an egg dropped by a commander, the player cannot then evolve to another lifeform in the same life. The evolve menu correctly displays lifeforms colored in that you can evolve to, but clicking the button does not evolve(behavior identical to trying to evolve outside navmesh).

There has been a lot of strange behavior surrounding this bug. For instance, Red is reporting he could do some evolutions locally, that I could not do online on TA(presumably this is caused by another interaction with another mod).

Here is a table of evolutions that Red could do

```
Lerk < Onos = Not Okay
Self Lerk < Fade = Okay
Comm Lerk < Onos = Not Okay
Comm Lerk < Fade = Okay
Comm Lerk > Gorge = Okay
Self Lerk > Gorge = Okay

Self Fade < Onos = Okay
Commander Fade < Onos = Okay
Self Fade > Gorge = Okay
Comm Fade > Gorge = Okay
Self Fade > Lerk = Okay
Comm Fade > Lerk = Okay

Self Onos > Gorge = Okay
Self Onos > Fade = Okay
Self Onos > Lerk = Not Okay
Commander Onos > Gorge = Okay
Commander Onos > Fade = Okay
Commander Onos > Lerk = Not Okay

Gorge - All evolves work including commander egg drops
```

**Comment by GhoulofGSG9** [comment] 2019-11-27 12:27
Can't reproduce this issue. Closing it for now, feel free to re-open it if the issue still occurs for you.

**Closed as completed by GhoulofGSG9** 2019-11-27 12:27 UTC
Labels: bug
